--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.8) ~  Much Love, Ferib 

]]--

local v0=os.clock();local v1=loadstring(game:HttpGet("https://cdn.keyguardian.org/library/v1.0.0.lua"))();local v2="335c42844e634b09ad72fd645207eee0";local v3="72d05c65a9924465974624da1c696bd7";v1.Set({publicToken="b88c31a0112f466aa50ddb4540ced147",privateToken="24ced444c3ad4d26abf8ee98cf37daaa",trueData=v2,falseData=v3});local v4="KeyGuard.txt";local function v5(v9,v10) game:GetService("StarterGui"):SetCore("SendNotification",{Title=v9,Text=v10,Duration=1070 -(68 + 997) });end local function v6() local v11=loadstring(game:HttpGet("https://github.com/dawid-scripts/Fluent/releases/latest/download/main.lua"))();local v12=v11:CreateWindow({Title="Key System",SubTitle="fx_Scripts",TabWidth=1430 -(226 + 1044) ,Size=UDim2.fromOffset(580,340),Acrylic=True,Theme="Light",MinimizeKey=Enum.KeyCode.H});local v13={KeySys=v12:AddTab({Title="Key System",Icon="key"})};local v14=v13.KeySys:AddInput("InputKey",{Title="Input Key",Description="Insert your key...",Default="",Placeholder="Enter key…",Numeric=false,Finished=false});local v15=v13.KeySys:AddButton({Title="Check Key",Description="Enter Key before pressing this button",Callback=function() local v17=0 -0 ;local v18;while true do if (v17==(118 -(32 + 85))) then if (v18==v2) then print("Key is valid");writefile(v4,v14.Value);v5("Success!","✅ Key Saved!");wait(1 + 0 );v12:Destroy();loadstring(game:HttpGet("https://raw.githubusercontent.com/fx2024ondiscord/roblox/refs/heads/main/SSL.%5Bfx%5D/Mobile%2BP/MCODE"))();else print("Key is invalid");v5("Error!","❌ Key is invalid.");end break;end if (v17==(0 + 0)) then print(v14.Value);v18=v1.validateDefaultKey(v14.Value);v17=1;end end end});local v16=v13.KeySys:AddButton({Title="Get Key",Description="Get Key here",Callback=function() setclipboard(v1.getLink());v5("Copied!","🔗 Key link copied to clipboard!");end});v12:SelectTab(958 -(892 + 65) );end if isfile(v4) then local v19=0 -0 ;local v20;while true do if (v19==(0 -0)) then v20=readfile(v4);if (v20 and (v20~="")) then local v21=0;local v22;local v23;local v24;local v25;while true do if (v21==(3 -1)) then print("Time taken to verify stored key: "   .. v25   .. " seconds" );if (v23==v2) then local v26=350 -(87 + 263) ;while true do if (v26==(180 -(67 + 113))) then print("Saved Key is valid");v5("Success!","✅ Saved Key is valid!");v26=1;end if (v26==(1 + 0)) then loadstring(game:HttpGet("https://raw.githubusercontent.com/fx2024ondiscord/roblox/refs/heads/main/SSL.%5Bfx%5D/Mobile%2BP/MCODE"))();break;end end else local v27=0 -0 ;while true do if ((0 + 0)==v27) then print("Saved Key is invalid");v5("Error!","❌ Saved Key is invalid.");v27=3 -2 ;end if (v27==(953 -(802 + 150))) then delfile(v4);v6();break;end end end break;end if (v21==(2 -1)) then v24=os.clock();v25=v24-v22 ;v21=3 -1 ;end if (v21==0) then v22=os.clock();v23=v1.validateDefaultKey(v20);v21=1 + 0 ;end end else v6();end break;end end else v6();end local v7=os.clock();local v8=v7-v0 ;print("Time taken to load everything: "   .. v8   .. " seconds" );
